# Generated by Django 5.1.6 on 2025-04-22 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_contact_first_name_alter_contact_last_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
    ]
