services:
  - type: web
    name: coursework
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn coursework.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src