services:
  - type: web
    name: coursework
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn coursework.wsgi:application --pythonpath coursework --bind 0.0.0.0:$PORT