services:
  - type: web
    name: myApp
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn coursework.coursework.wsgi:application --bind 0.0.0.0:$PORT