services:
  - type: web
    name: coursework
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      cd coursework && gunicorn coursework.wsgi:application --bind 0.0.0.0:$PORT