services:
  - type: web
    name: coursework
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      PYTHONPATH=/opt/render/project/src 
      gunicorn coursework.coursework.wsgi:application --bind 0.0.0.0:$PORT